using System;
using System.IO;
using System.Security;
using System.Text;
using DrawioPpt.Core.Models;

namespace DrawioPpt.PowerPointAddIn.Services
{
    public class DiagramVisualSvgService
    {
        public string WritePreviewSvg(DiagramEnvelope envelope)
        {
            if (envelope == null)
            {
                throw new ArgumentNullException("envelope");
            }

            string outputPath = BuildSvgPath(envelope.DiagramId);
            string directory = Path.GetDirectoryName(outputPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(outputPath, BuildSvgMarkup(envelope), Encoding.UTF8);
            return outputPath;
        }

        private static string BuildSvgPath(string diagramId)
        {
            string targetDirectory = Path.Combine(Path.GetTempPath(), "DrawioPpt", "svg");
            string safeId = string.IsNullOrWhiteSpace(diagramId) ? Guid.NewGuid().ToString("N") : diagramId;
            return Path.Combine(targetDirectory, safeId + ".svg");
        }

        private static string BuildSvgMarkup(DiagramEnvelope envelope)
        {
            string name = Escape(envelope.DiagramName);
            string diagramId = Escape(envelope.DiagramId);
            string editorTarget = Escape(envelope.EditorTarget);
            string updatedUtc = Escape(envelope.UpdatedUtc.ToString("u"));
            string sidecarPath = Escape(envelope.SidecarPath);

            return
                "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"960\" height=\"540\" viewBox=\"0 0 960 540\">" +
                "<defs>" +
                "<linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">" +
                "<stop offset=\"0%\" stop-color=\"#f5fbff\"/>" +
                "<stop offset=\"100%\" stop-color=\"#d6ecff\"/>" +
                "</linearGradient>" +
                "</defs>" +
                "<rect x=\"0\" y=\"0\" width=\"960\" height=\"540\" rx=\"32\" fill=\"url(#bg)\"/>" +
                "<rect x=\"28\" y=\"28\" width=\"904\" height=\"484\" rx=\"24\" fill=\"#ffffff\" stroke=\"#1f5fa8\" stroke-width=\"4\"/>" +
                "<circle cx=\"90\" cy=\"84\" r=\"20\" fill=\"#1f5fa8\"/>" +
                "<rect x=\"130\" y=\"66\" width=\"300\" height=\"32\" rx=\"16\" fill=\"#1f5fa8\" opacity=\"0.10\"/>" +
                "<text x=\"64\" y=\"160\" font-size=\"42\" font-family=\"Segoe UI, Arial, sans-serif\" font-weight=\"700\" fill=\"#17324d\">" + name + "</text>" +
                "<text x=\"64\" y=\"214\" font-size=\"22\" font-family=\"Consolas, Courier New, monospace\" fill=\"#255987\">Diagram ID: " + diagramId + "</text>" +
                "<text x=\"64\" y=\"258\" font-size=\"18\" font-family=\"Segoe UI, Arial, sans-serif\" fill=\"#3d5368\">This is a vector preview generated by DrawioPpt.</text>" +
                "<text x=\"64\" y=\"296\" font-size=\"18\" font-family=\"Segoe UI, Arial, sans-serif\" fill=\"#3d5368\">External editor: " + editorTarget + "</text>" +
                "<text x=\"64\" y=\"334\" font-size=\"18\" font-family=\"Segoe UI, Arial, sans-serif\" fill=\"#3d5368\">Last update (UTC): " + updatedUtc + "</text>" +
                "<text x=\"64\" y=\"372\" font-size=\"18\" font-family=\"Segoe UI, Arial, sans-serif\" fill=\"#3d5368\">Working file: " + sidecarPath + "</text>" +
                "<path d=\"M640 150 L820 150 L860 210 L860 390 L640 390 Z\" fill=\"#dff1ff\" stroke=\"#1f5fa8\" stroke-width=\"4\"/>" +
                "<path d=\"M680 220 C720 180 790 180 820 230 C840 265 828 315 790 338 C742 366 689 349 668 307 C654 279 657 245 680 220 Z\" fill=\"#7ec8ff\" stroke=\"#1f5fa8\" stroke-width=\"4\"/>" +
                "<path d=\"M716 248 L772 248 M744 220 L744 276\" stroke=\"#ffffff\" stroke-width=\"12\" stroke-linecap=\"round\"/>" +
                "<text x=\"640\" y=\"438\" font-size=\"20\" font-family=\"Segoe UI, Arial, sans-serif\" fill=\"#17324d\">Preview will be replaced after export succeeds.</text>" +
                "</svg>";
        }

        private static string Escape(string value)
        {
            return SecurityElement.Escape(value ?? string.Empty);
        }
    }
}

